# Generated by Django 5.2.17 on 2026-08-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="experience_level",
            field=models.CharField(default="Entry Level", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_job_type",
            field=models.CharField(default="Full-time", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_location",
            field=models.CharField(default="Delhi NCR", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="target_companies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="target_role",
            field=models.CharField(default="Software Engineer", max_length=100),
        ),
    ]
