from django.db import models
from django.conf import settings


class InterviewSession(models.Model):

    INTERVIEW_TYPES = [
        ("hr", "HR"),
        ("technical", "Technical"),
    ]

    STATUS_CHOICES = [
        ("active", "Active"),
        ("completed", "Completed"),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="interview_sessions"
    )

    interview_type = models.CharField(
        max_length=20,
        choices=INTERVIEW_TYPES
    )

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="active"
    )

    started_at = models.DateTimeField(
        auto_now_add=True
    )

    completed_at = models.DateTimeField(
        null=True,
        blank=True
    )

    question_count = models.PositiveIntegerField(
        default=0
    )

    def __str__(self):
        return (
            f"{self.user.email} - "
            f"{self.interview_type} - "
            f"{self.id}"
        )
        
class InterviewTurn(models.Model):

    session = models.ForeignKey(
        InterviewSession,
        on_delete=models.CASCADE,
        related_name="turns"
    )

    sequence = models.PositiveIntegerField()

    question = models.TextField()

    candidate_audio = models.FileField(
        upload_to="interviews/audio/",
        null=True,
        blank=True
    )

    transcript = models.TextField(
        blank=True
    )

    ai_response = models.TextField(
        blank=True
    )

    ai_audio = models.FileField(
        upload_to="interviews/ai_audio/",
        null=True,
        blank=True
    )

    # Later: acoustic + M3 results
    speech_features = models.JSONField(
        null=True,
        blank=True
    )

    m3_predictions = models.JSONField(
        null=True,
        blank=True
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        ordering = ["sequence"]

    def __str__(self):
        return f"Session {self.session_id} - Turn {self.sequence}"
    
class InterviewEvaluation(models.Model):

    session = models.OneToOneField(
        InterviewSession,
        on_delete=models.CASCADE,
        related_name="evaluation"
    )

    # Common evaluation dimensions
    communication_score = models.PositiveIntegerField()
    confidence_score = models.PositiveIntegerField()
    answer_quality_score = models.PositiveIntegerField()

    # HR-specific
    speaking_skills_score = models.PositiveIntegerField(
        null=True,
        blank=True
    )

    behavioral_performance_score = models.PositiveIntegerField(
        null=True,
        blank=True
    )

    # Technical-specific
    technical_performance_score = models.PositiveIntegerField(
        null=True,
        blank=True
    )
    accuracy_score = models.PositiveIntegerField(
        null=True,
        blank=True
    )

    # Calculated by our backend, NOT the LLM
    overall_score = models.PositiveIntegerField()

    # Dynamically generated by the LLM
    insights = models.JSONField()

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return (
            f"Evaluation - "
            f"Session {self.session_id}"
        )
        
class InterviewEvaluation(models.Model):

    session = models.OneToOneField(
        InterviewSession,
        on_delete=models.CASCADE,
        related_name="evaluation"
    )

    overall_score = models.FloatField(
        default=0
    )

    communication_score = models.FloatField(
        default=0
    )

    confidence_score = models.FloatField(
        default=0
    )

    answer_quality_score = models.FloatField(
        default=0
    )

    technical_performance_score = models.FloatField(
        null=True,
        blank=True
    )

    accuracy_score = models.FloatField(
        null=True,
        blank=True
    )

    speaking_skills_score = models.FloatField(
        null=True,
        blank=True
    )

    behavioral_performance_score = models.FloatField(
        null=True,
        blank=True
    )

    insights = models.JSONField(
        default=dict
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return (
            f"Evaluation - "
            f"Session {self.session_id}"
        )