# Generated by Django 5.2.17 on 2026-09-21 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[("hr", "HR"), ("technical", "Technical")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("question_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("question", models.TextField()),
                (
                    "candidate_audio",
                    models.FileField(
                        blank=True, null=True, upload_to="interviews/audio/"
                    ),
                ),
                ("transcript", models.TextField(blank=True)),
                ("ai_response", models.TextField(blank=True)),
                (
                    "ai_audio",
                    models.FileField(
                        blank=True, null=True, upload_to="interviews/ai_audio/"
                    ),
                ),
                ("speech_features", models.JSONField(blank=True, null=True)),
                ("m3_predictions", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="mock_interview.interviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
    ]
