# Generated by Django 5.2.17 on 2026-09-21 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_interview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("communication_score", models.PositiveIntegerField()),
                ("confidence_score", models.PositiveIntegerField()),
                ("answer_quality_score", models.PositiveIntegerField()),
                (
                    "speaking_skills_score",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "behavioral_performance_score",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "technical_performance_score",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("accuracy_score", models.PositiveIntegerField(blank=True, null=True)),
                ("overall_score", models.PositiveIntegerField()),
                ("insights", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="mock_interview.interviewsession",
                    ),
                ),
            ],
        ),
    ]
