# Generated by Django 5.2.17 on 2026-09-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mock_interview", "0002_interviewevaluation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewevaluation",
            name="accuracy_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interviewevaluation",
            name="answer_quality_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="interviewevaluation",
            name="behavioral_performance_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interviewevaluation",
            name="communication_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="interviewevaluation",
            name="confidence_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="interviewevaluation",
            name="insights",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="interviewevaluation",
            name="overall_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="interviewevaluation",
            name="speaking_skills_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interviewevaluation",
            name="technical_performance_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
