# Generated by Django 5.2.17 on 2026-09-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_coach", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="coachconversation",
            new_name="ai_coach_co_user_id_3f9add_idx",
            old_name="ai_coach_c_user_id_9a2d2e_idx",
        ),
        migrations.RenameIndex(
            model_name="coachmessage",
            new_name="ai_coach_co_convers_e9c8da_idx",
            old_name="ai_coach_c_convers_6b1e0c_idx",
        ),
    ]
